#!/bin/bash

rm -f filenames.txt
rm -f frequencies.high
rm -f frequent.words
rm -f log.print
rm -f output.temp
rm -f POS.lm
rm -f test.dict
rm -f test.labelled
rm -f test.phrases
rm -fr test_results/
rm -f test.temp
rm -f toremove.words
rm -f train.dict
rm -f train.fst
rm -f train.phrases
rm -f train.POS.counts
rm -f train.symb
rm -f train.tags-phrase.cnt
rm -f train.tags-phrase.far
rm -f train.tags-phrase.lines
rm -f train.TOK-POS.counts
rm -f train.TOK-POS.probs
rm -f train.TOK-POS.states
rm -f train.total.states
rm -f train.unk.states
rm -f train.TOK-POS.temp2
rm -f words.cutoff